create table if not exists public.persons (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  uid           UUID REFERENCES auth.users NULL,
  firstname     TEXT NULL,
  middlename    TEXT NULL,
  lastname      TEXT NULL,
  nickname      TEXT NULL,
  company       TEXT NULL,
  photourl      TEXT NULL,
  dob           DATE NULL,
  anniversary   DATE NULL,  
  notes         TEXT NULL,
  address       JSONB NULL,
  email         JSONB NULL,
  instantmessage JSONB NULL,
  phone         JSONB NULL,
  relation      JSONB NULL,
  socialprofile JSONB NULL,
  url           JSONB NULL,
  created_at    TIMESTAMP DEFAULT NOW(),
  updated_at    TIMESTAMP DEFAULT NOW(),
  created_by    UUID REFERENCES auth.users,
  metadata      JSONB NULL,
  xtra          JSONB NULL
);

